import { z } from 'zod'
import { FileEntrySchema, SideSchema } from './review-artifact.js'
import { ReviewKeySchema } from './review-key.js'

/**
 * The self-review deck: decision cards the author picks a side of before reviewers see the change.
 * The deck is its own artifact, generated by its own skill (ADR 0004); it meets the canvas only
 * through the settled decisions it leaves behind.
 */

/** What a card is about. The prompt lists the questions each bucket covers. */
export const CARD_BUCKETS = ['trade-off', 'intent', 'shape', 'risk'] as const
export type CardBucket = (typeof CARD_BUCKETS)[number]

/** The two sides of a card. The page draws `a` on the left and `b` on the right. */
export const CARD_SIDES = ['a', 'b'] as const
export type CardSide = (typeof CARD_SIDES)[number]

/**
 * Where a settled decision's justification is kept: as the author's own comment for the pull
 * request, in the code or docs (the fix skill writes it), or nowhere because the code says it.
 */
export const RECORD_TARGETS = ['pr-comment', 'code', 'none'] as const
export type RecordTarget = (typeof RECORD_TARGETS)[number]

/** Visible-character caps. One card has to fit a 1080p screen with no scroll. */
export const DECK_CAPS = {
  title: 60,
  topic: 40,
  context: 240,
  label: 48,
  consequence: 200,
  why: 140,
  note: 240,
} as const

/** Lines of code a side may show; more than that belongs in the diff drawer. */
export const SNIPPET_MAX_LINES = 8

/** Card keys name a card across re-decks, so they are short, stable slugs. */
export const CARD_KEY_RE = /^[a-z0-9][a-z0-9-]{0,47}$/

const text = (cap: number) =>
  z
    .string()
    .regex(/\S/, 'must contain visible text')
    .max(cap * 4)

export const SnippetSchema = z.object({
  /** A highlight.js language name; omitted means the anchor file's language. */
  lang: z.string().min(1).optional(),
  code: z.string().min(1),
})
export type Snippet = z.infer<typeof SnippetSchema>

export const CardSideSchema = z.object({
  label: text(DECK_CAPS.label),
  consequence: text(DECK_CAPS.consequence),
  snippet: SnippetSchema.optional(),
  /** The one-line justification the author accepts by picking this side, or edits first. */
  why: text(DECK_CAPS.why),
  record: z.enum(RECORD_TARGETS),
})
export type CardSideContent = z.infer<typeof CardSideSchema>

export const DecisionCardSchema = z.object({
  key: z.string().regex(CARD_KEY_RE, 'a card key is a lowercase slug of at most 48 characters'),
  bucket: z.enum(CARD_BUCKETS),
  /** The kind of choice in a few words, such as "Back-compat vs clean break". */
  topic: text(DECK_CAPS.topic),
  title: text(DECK_CAPS.title),
  context: text(DECK_CAPS.context),
  path: z.string().min(1),
  line: z.number().int().positive(),
  side: SideSchema.optional(),
  /** Which side the code implements now; null when it does neither. */
  current: z.enum(CARD_SIDES).nullable(),
  a: CardSideSchema,
  b: CardSideSchema,
})
export type DecisionCard = z.infer<typeof DecisionCardSchema>

/** What the generator writes: `deck-model.json`. */
export const DeckModelSchema = z.object({ cards: z.array(DecisionCardSchema) })
export type DeckModel = z.infer<typeof DeckModelSchema>

/** The author's answer to one card. `skip` hands the card to reviewers as an open decision. */
export const PickChoiceSchema = z.enum(['a', 'b', 'neither', 'skip'])
export type PickChoice = z.infer<typeof PickChoiceSchema>

export const PickSchema = z.object({
  choice: PickChoiceSchema,
  /** The justification as the author left it: the picked side's `why`, edited or not. */
  why: z
    .string()
    .max(DECK_CAPS.why * 4)
    .optional(),
  /** What the author wants instead, when neither side fits. */
  note: z
    .string()
    .max(DECK_CAPS.note * 4)
    .optional(),
  record: z.enum(RECORD_TARGETS).optional(),
  pickedAt: z.string(),
})
export type Pick = z.infer<typeof PickSchema>

/** A card the author settled in an earlier deck of this review, carried as it stands. */
export const SettledCardSchema = DecisionCardSchema.extend({
  pick: PickSchema,
  /** The head the card was generated for. */
  headSha: z.string().regex(/^[0-9a-f]{40}$/),
})
export type SettledCard = z.infer<typeof SettledCardSchema>

/** `deck.json`: the published deck of one review: a pull request, or a local review. */
export const DeckSchema = z.object({
  version: z.literal(1),
  review: ReviewKeySchema,
  headSha: z.string().regex(/^[0-9a-f]{40}$/),
  mergeBaseSha: z.string().regex(/^[0-9a-f]{40}$/),
  baseRef: z.string(),
  headRef: z.string(),
  generatedAt: z.string(),
  generator: z.object({ agent: z.string().min(1), model: z.string().optional() }),
  cards: z.array(DecisionCardSchema),
  /** Decisions settled in earlier decks, which this deck never asks again. */
  settled: z.array(SettledCardSchema),
})
export type Deck = z.infer<typeof DeckSchema>

/** `picks.json`: the author's answers to the current deck's cards, by card key. */
export const PicksSchema = z.object({ picks: z.record(z.string(), PickSchema) })
export type Picks = z.infer<typeof PicksSchema>

/**
 * `posted.json`: the settled decisions already posted as the author's comments on a pull request,
 * by card key, so publishing the canvas again never posts one twice. A pick changed since posts anew.
 */
export const PostedSchema = z.object({
  posted: z.record(z.string(), z.object({ pickedAt: z.string(), url: z.string() })),
})
export type Posted = z.infer<typeof PostedSchema>

/** The body of `PUT /api/deck/:key/picks/:card`. */
export const PickBodySchema = z.object({
  headSha: z.string().regex(/^[0-9a-f]{40}$/),
  choice: PickChoiceSchema,
  why: z
    .string()
    .max(DECK_CAPS.why * 4)
    .optional(),
  note: z
    .string()
    .max(DECK_CAPS.note * 4)
    .optional(),
  record: z.enum(RECORD_TARGETS).optional(),
})
export type PickBody = z.infer<typeof PickBodySchema>

/**
 * `work/context.json`: what `deck prepare` resolved, so `deck publish` validates against the same
 * diff and cap, and carries the same settled decisions, whatever changed in between.
 */
export const DeckContextSchema = z.object({
  version: z.literal(1),
  review: ReviewKeySchema,
  base: z.string().min(1),
  headRef: z.string(),
  headSha: z.string().regex(/^[0-9a-f]{40}$/),
  mergeBaseSha: z.string().regex(/^[0-9a-f]{40}$/),
  files: z.array(FileEntrySchema),
  changedLines: z.number().int().nonnegative(),
  maxCards: z.number().int().nonnegative(),
  modelPath: z.string().min(1),
  settled: z.array(SettledCardSchema),
  preparedAt: z.string(),
})
export type DeckContext = z.infer<typeof DeckContextSchema>

export interface SelfReviewLimits {
  maxCards: number
  linesPerCard: number
}

/**
 * How many new cards a deck may hold: one per `linesPerCard` changed lines, rounded up, never
 * more than `maxCards`. Zero cards is always a valid deck; the cap only bounds it.
 */
export function deckCardCap(changedLines: number, limits: SelfReviewLimits): number {
  if (changedLines <= 0) {
    return 0
  }
  return Math.min(limits.maxCards, Math.ceil(changedLines / limits.linesPerCard))
}

/** True when the author's pick asks the code to change: another side, or neither side. */
export function pickNeedsFix(card: DecisionCard, pick: Pick): boolean {
  if (pick.choice === 'skip') {
    return false
  }
  return pick.choice === 'neither' || pick.choice !== card.current
}
